Update IPQ60XX-24.10(NOWIFI).yml

diff --git a/.github/workflows/IPQ60XX-24.10(NOWIFI).yml b/.github/workflows/IPQ60XX-24.10(NOWIFI).yml
--- a/.github/workflows/IPQ60XX-24.10(NOWIFI).yml
+++ b/.github/workflows/IPQ60XX-24.10(NOWIFI).yml
@@ -85,8 +85,10 @@ jobs:
 
     - name: Load Custom Configuration(加载自定义配置)
       run: |
-        [ -e files ] && mv files openwrt/files
-        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
+        echo "Looking for config file: $CONFIG_FILE"
+        ls -l $CONFIG_FILE || { echo "ERROR: $CONFIG_FILE not found!"; exit 1; }
+        [ -d files ] && cp -r files openwrt/
+        [ -f $CONFIG_FILE ] && cp $CONFIG_FILE openwrt/.config
 
 
     - name: Download DL Package(下载DL软件包)
